export enum MUTATION_KEY {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  FRUIT_CREATE = "FRUIT_CREATE",
  FRUIT_EDIT = "FUIT_EDIT",
  FRUIT_DELETE = "FRUIT_DELETE",
}

export enum QUERY_KEY {
  FUIRT_LIST = "FUIRT_LIST",
  FUIRT_DETAIL = "FUIRT_DETAIL",
}
